@Library('shared_libs') _
import pipeline.stage.checkout.config.GitConfig
import pipeline.stage.checkout.config.CheckoutConfigStage

def pipeline
node {
  def workSpacePath = env.WORKSPACE + "@libs/shared_libs/"
  println(workSpacePath)

  def stagesPath = "/vars/stage/"
  def checkoutStageFileName ="CheckoutStage.groovy"

  println("Load file with checkout stage '" + checkoutStageFileName + "'")
  pipeline = load(workSpacePath + stagesPath + checkoutStageFileName)
  println("File '"+ checkoutStageFileName +"' was successfully loaded")

  def checkoutConfig = new  CheckoutConfigStage()
  checkoutConfig.setStageName("Shop checkout")
  def gitConfig = new GitConfig()
  gitConfig.setUrl("https://github.com/DmitryYusupov/shop.git")
  gitConfig.setBrunch("master")
  checkoutConfig.setGitConfig(gitConfig)

  pipeline.doCheckout(checkoutConfig)
  println("Checkout has SUCCESSFULLY finished!")

}