@Library('global_libs') _
import pipeline.stages.common.config.reader.ConfigReader
node {
  def  configs = ConfigReader.parsePipelineConfig("C:\\Users\\Dmitry_Yusupov\\Desktop\\Jenkins_pipeline\\jenkinspipeline\\projects\\Shop\\pipeline.xml")

  javaUtils.setJavaHome("Java_11")
  //---checkout----
  stageCheckout.doCheckout(configs.checkoutStageConfig)

  //---stage build----
  stageBuild.doBuild(configs.buildStageConfig)
}